python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 0 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 2 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 3 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 4 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 6 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 8 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 11 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 12 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 14 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 15 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 18 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 19 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 20 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 21 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 22 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 24 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 28 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 29 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 31 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 32 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 33 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 34 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 40 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 41 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 43 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 44 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 46 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 48 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 50 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 53 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 54 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 57 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 59 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 60 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 61 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 66 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 67 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 68 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 70 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 72 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 73 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 76 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 77 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 81 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 86 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 89 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 90 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 92 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 93 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 94 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 96 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 99 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 100 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 102 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 103 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 104 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 107 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 108 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 111 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 113 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 114 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 118 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 121 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 123 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 125 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 128 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 130 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 135 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 136 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 140 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 146 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 148 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 149 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 151 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 153 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 155 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 158 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 159 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 160 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 169 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 175 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 178 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 181 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 183 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 184 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 186 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 191 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 192 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 193 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 194 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 195 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 198 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 203 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 204 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 205 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 207 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 208 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 209 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 213 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 218 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 222 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 223 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 225 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 227 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 236 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 238 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 239 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 243 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 248 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 251 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 257 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 258 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 259 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 260 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 261 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 262 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 266 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 268 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 272 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 275 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 283 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 284 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 285 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 289 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 290 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 291 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 292 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 298 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 301 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 303 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 307 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 308 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 309 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 313 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 314 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 315 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 318 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 319 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 320 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 322 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 323 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 324 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 328 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 331 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 333 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 334 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 335 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 336 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 339 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 341 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 342 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 344 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 347 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 350 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 352 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 354 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 355 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 356 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 359 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 361 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 365 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 367 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 370 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 376 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 379 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 380 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 382 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 383 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 384 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 387 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 391 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 394 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 398 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 400 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 402 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 403 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 404 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 405 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 408 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 411 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 414 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 417 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 418 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 419 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 422 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 426 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 428 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 431 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 434 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 435 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 438 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 442 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 444 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 448 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 449 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 451 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 452 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 457 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 461 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 463 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 471 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 472 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 473 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 478 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 479 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 480 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 484 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 486 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 488 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 489 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 492 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 495 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 497 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 498 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 500 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 501 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 505 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 506 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 509 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 517 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 518 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 519 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 520 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 522 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 524 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 526 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 527 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 528 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 530 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 532 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 539 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 542 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 543 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 545 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 548 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 550 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 551 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 553 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 554 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 556 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 560 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 561 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 564 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 565 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 566 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 574 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 577 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 578 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 579 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 581 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 583 --role fitting --use_multiscan 0 --ablation_param none
python -u /home1/08171/zheyw1/Alzh_tau_abeta_model_new/main_clinical.py --pat_ids 584 --role fitting --use_multiscan 0 --ablation_param none
